### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by julianfairfax** [flathub/de.haeckerfelix.Fragments#20] opened 2023-09-28 20:22 UTC
The `host` permission is quite vast.  Why does it need access to the entire filesystem? As far as I'm aware, it can download to any folder through a portal. It doesn't need constant access to a user's system?

**Comment by haecker-felix** [comment] 2024-03-24 21:27
Duplicate of https://gitlab.gnome.org/World/Fragments/-/issues/189

**Closed by haecker-felix** 2024-03-24 21:27 UTC
